alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true

  adminPassword: "StrongPassword123!"  

  env:
    GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana"
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: main
    hosts:
      - ""
    path: /grafana
    pathType: Prefix

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1536Mi

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

nodeExporter:
  enabled: true