name: "Infrastructure DOWN"

on:
  workflow_dispatch: # Включает кнопку ручного запуска в UI GitHub

permissions:
  id-token: write # Обязательно для генерации токена AWS OIDC
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262778473495:role/GitHubActionsEKSRole
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0" 

      - name: Terraform Init
        run: |
          cd aws-eks-infra
          terraform init

   
      - name: Terraform Destroy
        run: |
          cd aws-eks-infra
          terraform destroy -auto-approve
