name: "Infrastructure UP"

on:
  workflow_dispatch:
    inputs:
      local_admin_principal_arn:
        description: "Optional IAM user/role ARN for local kubectl admin access"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-infra
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: aws-eks-infra
  TF_VERSION: "1.11.0"
  TF_VAR_local_admin_principal_arn: ${{ inputs.local_admin_principal_arn }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262778473495:role/GitHubActionsEKSRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
